name: Package single ADF pipeline -> JFrog (test)

on:
  workflow_dispatch:   # manual test run on this branch
  push:
    branches:
      - adf_publish     # once merged to main/default this will run when ADF publishes

jobs:
  package_single_pipeline:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Show repo root (debug)
        run: ls -la

      - name: Verify pipeline file exists
        id: check
        run: |
          PIPE_PATH="pipeline/Migration_CRM_Sync_Procedure.json"
          echo "Checking for $PIPE_PATH"
          if [ ! -f "$PIPE_PATH" ]; then
            echo "::error file=$PIPE_PATH::Pipeline file not found. Aborting."
            exit 1
          fi
          echo "found=1" >> $GITHUB_OUTPUT
          echo "PIPE_PATH=$PIPE_PATH" >> $GITHUB_OUTPUT

      - name: Create ZIP containing only the pipeline file
        if: steps.check.outputs.found == '1'
        id: makezip
        run: |
          mkdir -p build
          ZIPNAME="pipeline_Migration_CRM_Sync_${{ github.run_number }}.zip"
          PIPE="${{ steps.check.outputs.PIPE_PATH }}"
          echo "Creating build/$ZIPNAME with $PIPE"
          zip -j "build/$ZIPNAME" "$PIPE" >/dev/null
          echo "ZIPNAME=$ZIPNAME" >> $GITHUB_OUTPUT
          echo "ZIPPATH=build/$ZIPNAME" >> $GITHUB_OUTPUT

      - name: List build dir for debug
        run: ls -la build || true

      - name: Setup JFrog CLI
        uses: jfrog/setup-jfrog-cli@v2

      - name: Configure JFrog CLI
        env:
          JFROG_URL: ${{ secrets.JFROG_URL }}
          JFROG_API_KEY: ${{ secrets.JFROG_API_KEY }}
        run: |
          jfrog rt config --url="$JFROG_URL" --apikey="$JFROG_API_KEY" --interactive=false

      - name: Upload pipeline ZIP to JFrog
        env:
          JFROG_REPO: ${{ secrets.JFROG_REPO }}
        run: |
          ZIPFILE="${{ steps.makezip.outputs.ZIPNAME }}"
          SRC="build/$ZIPFILE"
          DST="${JFROG_REPO}/${ZIPFILE}"
          echo "Uploading $SRC -> $DST"
          jfrog rt u "$SRC" "$DST" --flat=true
          jfrog rt s "$DST"

      - name: Output artifact info
        run: echo "Uploaded to JFrog as: ${{ secrets.JFROG_REPO }}/${{ steps.makezip.outputs.ZIPNAME }}"
